###
GET HTTP://localhost:9000/api/publisher

###
POST http://localhost:9000/api/publisher_create
Content-Type: application/json

{
    "name" : "komic"
}

###
GET http://localhost:9000/api/publisher_read_all


###
GET http://localhost:9000/api/books_read_all